name: MaxShields
favicon: null
layout_spectrum: 1
typography_spectrum: 0.65626
title: 'Artist, Photographer, Author, Game Developer'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9f9594'
    - '#2c4c15'
    - '#250706'
    - '#99231f'
    - '#f2af8d'
  brandStrength: 0
  lightness: 1
  saturation: 0
  rhythmicContrast: 1
purpose: []
