name: MaxShields
favicon: null
layout_spectrum: 0.74883
typography_spectrum: 0.65626
title: 'Artist, Photographer, Author, Game Developer'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a5bbde'
    - '#92040b'
    - '#d2d0dd'
    - '#3c0103'
    - '#dc1d25'
  brandStrength: 0
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
